import json

from config import JINKU_CSRF_TOKEN, JINKU_COOKIE

BRANDS= {
    "1": "ACURA",
    "2": "ALFA ROMEO",
    "5": "AUDI",
    "6": "BENTLEY",
    "7": "BMW",
    "10": "BUICK (GM)",
    "12": "CADILLAC (GM)",
    "15": "CHEVROLET (GM)",
    "16": "CHRYSLER",
    "18": "CITROEN",
    "20": "DAEWOO",
    "22": "DAIHATSU",
    "24": "DODGE",
    "26": "FIAT",
    "27": "FORD",
    "28": "MERCURY (FORD)",
    "29": "FORD (USA)",
    "31": "HINO",
    "32": "HONDA",
    "35": "HUMMER",
    "36": "HYUNDAI",
    "37": "INFINITI",
    "38": "ISUZU",
    "39": "IVECO",
    "40": "JAGUAR",
    "42": "JEEP",
    "43": "KIA",
    "44": "LADA",
    "46": "LAND ROVER",
    "48": "LEXUS",
    "50": "LINCOLN",
    "55": "MAZDA",
    "56": "MAZDA JAPAN FORD",
    "58": "MERCEDES-BENZ",
    "60": "MINI",
    "61": "MITSUBISHI",
    "62": "NISSAN",
    "63": "NISSAN DIESEL UD",
    "66": "OPEL",
    "67": "OPEL (Vauxhall)",
    "68": "PERODUA",
    "69": "PEUGEOT",
    "72": "PONTIAC (GM)",
    "73": "PORSCHE",
    "74": "PROTON",
    "75": "RENAULT",
    "79": "SAAB",
    "81": "SEAT",
    "82": "SKODA",
    "83": "SMART",
    "84": "SSANGYONG",
    "85": "SUBARU",
    "86": "SUZUKI",
    "88": "TOYOTA",
    "90": "VOLVO",
    "91": "VOLKSWAGEN",
    "93": "HOLDEN",
    "96": "DACIA (Renault)",
    "100": "KOMATSU",
    "101": "SCANIA",
    "232": "GAZ",
    "237": "MG (SAIC)",
    "241": "UAZ",
    "285": "DATSUN",
    "354": "LIFAN",
    "424": "DONGFENG",
    "426": "LAMBORGHINI",
    "429": "MITSUOKA",
    "431": "GEELY",
    "440": "NAZA",
    "442": "MARUTI SUZUKI",
    "443": "TESLA",
    "445": "JAC",
    "446": "RAVON",
    "447": "BAW",
    "448": "CHERY",
    "449": "Great Wall Motors",
    "453": "BYD",
    "459": "MAN TGE Box",
    "462": "CHANGAN",
    "463": "GMC",
    "464": "BRILLIANCE",
    "466": "MAPLE (SMA)",
    "468": "GENESIS",
    "469": "SAMSUNG",
    "470": "FAW",
    "471": "PLYMOUTH",
    "472": "EXEED (CHERY)",
    "476": "GAC",
    "479": "HAVAL",
    "480": "CUPRA",
    "489": "OMODA (CHERY)",
    "496": "ZEEKR",
    "497": "TANK",
    "503": "RAM",
    "511": "KAIYI",
    "517": "JAECOO (CHERY)",
    "524": "SOLLERS",
    "527": "HONDA (GAC)",
    "528": "HONDA (DONGFENG)"
}


JINKU_CATALOG_URL="https://www.jikiu.com/livewire/message/search-catalogue"


USER_AGENTS = [
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Firefox/63.0',
    'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0'
]

JINKU_HEADERS = {
    'User-Agent': USER_AGENTS[1],  # Default to the first user agent
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
    'Accept-Language': 'en-US,en;q=0.5',
    'Accept-Encoding': 'gzip, deflate, br',
    'Connection': 'keep-alive',
    'Upgrade-Insecure-Requests': '1',
    'Referer': 'https://www.google.com/',
    'Origin': 'https://www.google.com/',
    'cookie':JINKU_COOKIE,
    'x-csrf-token': JINKU_CSRF_TOKEN,
    'x-livewire': 'true',
    'Content-Type': 'application/json',

}


JINKU_PAYLOAD ={
  "fingerprint": {
    "id": "DQXNGaS9vZ4NOTGzaIjz",
    "name": "search-catalogue",
    "locale": "en",
    "path": "catalogue",
    "method": "GET",
    "v": "acj"
  },
  "serverMemo": {
    "children": [],
    "errors": [],
    "htmlHash": "a58e6cbe",
    "data": {
      "brand": None,
      "model": None,
      "body": None,
      "year": None,
      "engine": None,
      "engineVolume": None,
      "partNumber": "",
      "profileType": None,
      "showSize": False,
      "sizeParameters": [],
      "requestParameters": [],
      "requestBody": None,
      "requestEngNo": None,
      "requestEngVol": None,
      "requestImg": None,
      "requestModel": None,
      "requestYear": 0,
      "is_home": True,
      "isParamSet": False,
      "vinNumber": "",
      "selectedProfileType": None,
      "specSizeAdjust": None,
      "partSuggestions": [],
      "brands": {
        "1": "ACURA",
        "2": "ALFA ROMEO",
        "5": "AUDI",
        "6": "BENTLEY",
        "7": "BMW",
        "10": "BUICK (GM)",
        "12": "CADILLAC (GM)",
        "15": "CHEVROLET (GM)",
        "16": "CHRYSLER",
        "18": "CITROEN",
        "20": "DAEWOO",
        "22": "DAIHATSU",
        "24": "DODGE",
        "26": "FIAT",
        "27": "FORD",
        "28": "MERCURY (FORD)",
        "29": "FORD (USA)",
        "31": "HINO",
        "32": "HONDA",
        "35": "HUMMER",
        "36": "HYUNDAI",
        "37": "INFINITI",
        "38": "ISUZU",
        "39": "IVECO",
        "40": "JAGUAR",
        "42": "JEEP",
        "43": "KIA",
        "44": "LADA",
        "46": "LAND ROVER",
        "48": "LEXUS",
        "50": "LINCOLN",
        "55": "MAZDA",
        "56": "MAZDA JAPAN FORD",
        "58": "MERCEDES-BENZ",
        "60": "MINI",
        "61": "MITSUBISHI",
        "62": "NISSAN",
        "63": "NISSAN DIESEL UD",
        "66": "OPEL",
        "67": "OPEL (Vauxhall)",
        "68": "PERODUA",
        "69": "PEUGEOT",
        "72": "PONTIAC (GM)",
        "73": "PORSCHE",
        "74": "PROTON",
        "75": "RENAULT",
        "79": "SAAB",
        "81": "SEAT",
        "82": "SKODA",
        "83": "SMART",
        "84": "SSANGYONG",
        "85": "SUBARU",
        "86": "SUZUKI",
        "88": "TOYOTA",
        "90": "VOLVO",
        "91": "VOLKSWAGEN",
        "93": "HOLDEN",
        "96": "DACIA (Renault)",
        "100": "KOMATSU",
        "101": "SCANIA",
        "232": "GAZ",
        "237": "MG (SAIC)",
        "241": "UAZ",
        "285": "DATSUN",
        "354": "LIFAN",
        "424": "DONGFENG",
        "426": "LAMBORGHINI",
        "429": "MITSUOKA",
        "431": "GEELY",
        "440": "NAZA",
        "442": "MARUTI SUZUKI",
        "443": "TESLA",
        "445": "JAC",
        "446": "RAVON",
        "447": "BAW",
        "448": "CHERY",
        "449": "Great Wall Motors",
        "453": "BYD",
        "459": "MAN TGE Box",
        "462": "CHANGAN",
        "463": "GMC",
        "464": "BRILLIANCE",
        "466": "MAPLE (SMA)",
        "468": "GENESIS",
        "469": "SAMSUNG",
        "470": "FAW",
        "471": "PLYMOUTH",
        "472": "EXEED (CHERY)",
        "476": "GAC",
        "479": "HAVAL",
        "480": "CUPRA",
        "489": "OMODA (CHERY)",
        "496": "ZEEKR",
        "497": "TANK",
        "503": "RAM",
        "511": "KAIYI",
        "517": "JAECOO (CHERY)",
        "524": "SOLLERS",
        "527": "HONDA (GAC)",
        "528": "HONDA (DONGFENG)"
      },
      "models": [],
      "bodies": [],
      "years": [],
      "engines": [],
      "engineVolumes": [],
      "profileTypes": [
        {
          "type_id": 230,
          "type_name": "BODY/FRAME BUSH"
        },
        {
          "type_id": 164,
          "type_name": "BUSH, SUSPENSION"
        },
        {
          "type_id": 166,
          "type_name": "DIFFERENTIAL MOUNTING"
        },
        {
          "type_id": 167,
          "type_name": "DRIVE SHAFT BOOT"
        },
        {
          "type_id": 257,
          "type_name": "ENGINE BUSHING"
        },
        {
          "type_id": 231,
          "type_name": "SHOCK ABSORBER BUSH"
        },
        {
          "type_id": 285,
          "type_name": "SPRING SHACKLE BUSH"
        },
        {
          "type_id": 258,
          "type_name": "SPRING SHACKLE RUBBER"
        },
        {
          "type_id": 181,
          "type_name": "STABILIZER BUSH"
        },
        {
          "type_id": 171,
          "type_name": "STEERING BUSH"
        },
        {
          "type_id": 182,
          "type_name": "STEERING GEAR BOOT"
        },
        {
          "type_id": 223,
          "type_name": "STRUT BAR RUBBER/BUSH"
        }
      ]
    },
    "dataMeta": [],
    "checksum": "d604b6700d4c37cdff1fb4bab423b632862e5a192dd87cfc0489af5d00c7e798"
  },
  "updates": [
    {
      "type": "callMethod",
      "payload": {
        "id": "lt06i",
        "method": "$set",
        "params": [
          "brand"
        ]
      }
    }
  ]
}