MODELS={"A-STAR":"P",
        "ALTO 800":"AA",
        "ALTO K10 (FROM AUG-2010)":"T",
        "ALTO K10 (FROM AUG-2022)":"Y0M",
        "ALTO K10 (FROM OCT-2014)":"TT",
        "BALENO (FROM FEB 2022)":"YTA",
        "BALENO (FROM OCT-2015)":"YRA",
        "BREZZA (FROM JUN 2022)":"YXA",
        "CELERIO":"CL",
        "CELERIO (FROM NOV-2021)":"YNC",
        "CIAZ":"CZ",
        "DZIRE (FROM FEB-2012)":"J",
        "DZIRE (FROM MAR-2008)":"S",
        "DZIRE (FROM MAY-2017)":"YSD",
        "DZIRE (FROM NOV-2024)":"YEDNB",
        "EECO":"R1",
        "ERTIGA (FROM APR-2012)":"Q",
        "ERTIGA (FROM NOV-2018)":"YHB",
        "FRONX":"YTB",
        "GRAND VITARA (FROM SEP-2022)":"YFG",
        "IGNIS":"YJC",
        "INVICTO":"YDA",
        "JIMNY":"YWD",
        "KIZASHI":"Z",
        "RITZ":"D",
        "S-CROSS":"YAD",
        "S-PRESSO":"Y1K",
        "SUPER CARRY":"Y9T",
        "SWIFT (FROM AUG-2011)":"H",
        "SWIFT (FROM FEB-2018)":"YSD11",
        "SWIFT (FROM JAN-2005)":"K",
        "SWIFT (FROM MAY-2024)":"YED11",
        "SX4":"F",
        "VITARA BREZZA":"YBA",
        "WAGON-R (FROM APR-2010)":"WR",
        "WAGON-R (FROM DEC-2018)":"YCA",
        "WAGON-R (FROM JAN-2000)":"B",
        "XL6":"YHC",
        "ZEN ESTILO":"M",
        }

