MODELS={"A-STAR":"P",
        "ALTO 800":"AA",
        "ALTO K10 (FROM AUG-2010)":"T",
        "ALTO K10 (FROM AUG-2022)":"Y0M",
        "ALTO K10 (FROM OCT-2014)":"TT",
        "BALENO (FROM FEB 2022)":"YTA",
        "BALENO (FROM OCT-2015)":"YRA",
        "BREZZA (FROM JUN 2022)":"YXA",
        "CELERIO":"CL",
        "CELERIO (FROM NOV-2021)":"YNC",
        "CIAZ":"CZ",
        "DZIRE (FROM FEB-2012)":"J",
        "DZIRE (FROM MAR-2008)":"S",
        "DZIRE (FROM MAY-2017)":"YSD",
        "DZIRE (FROM NOV-2024)":"YEDNB",
        "EECO":"R1",
        "ERTIGA (FROM APR-2012)":"Q",
        "ERTIGA (FROM NOV-2018)":"YHB",
        "FRONX":"YTB",
        "GRAND VITARA (FROM SEP-2022)":"YFG",
        "IGNIS":"YJC",
        "INVICTO":"YDA",
        "JIMNY":"YWD",
        "KIZASHI":"Z",
        "RITZ":"D",
        "S-CROSS":"YAD",
        "S-PRESSO":"Y1K",
        "SUPER CARRY":"Y9T",
        "SWIFT (FROM AUG-2011)":"H",
        "SWIFT (FROM FEB-2018)":"YSD11",
        "SWIFT (FROM JAN-2005)":"K",
        "SWIFT (FROM MAY-2024)":"YED11",
        "SX4":"F",
        "VITARA BREZZA":"YBA",
        "WAGON-R (FROM APR-2010)":"WR",
        "WAGON-R (FROM DEC-2018)":"YCA",
        "WAGON-R (FROM JAN-2000)":"B",
        "XL6":"YHC",
        "ZEN ESTILO":"M",
        }

SUZUKI_HEADERS = {
        "accept": "application/json, text/javascript, */*; q=0.01",
        "accept-language": "en-GB,en-US;q=0.9,en;q=0.8",
        "content-type": "application/json",
        "origin": "https://www.marutisuzuki.com",
        "priority": "u=1, i",
        "referer": "https://www.marutisuzuki.com/genuine-parts?utm_source=google&utm_medium=cpc&utm_campaign=MSGP_Brand_Search_Generic&utm_id=%7Bcampaignid%7D&utm_term=%7Bkeyword%7D&utm_content=search&utm_source=google&utm_medium=cpc&utm_campaign=22079570581&utm_term=maruti%20suzuki%20parts&utm_content=c&gad_source=1",
        "sec-ch-ua": '"Chromium";v="136", "Google Chrome";v="136", "Not.A/Brand";v="99"',
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": '"Linux"',
        "sec-fetch-dest": "empty",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "same-origin",
        "user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36",
        "x-requested-with": "XMLHttpRequest",
        "cookie": "marutisuzuki#lang=en"
    }
